name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  Build-and-Release:
    name: build and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: set variables
        run: |
          mkdir build
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "GOPRIVATE=github.com/v2ray/v2ray-core" >> $GITHUB_ENV
        shell: bash
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: build v2gen
        run: |
          LDFLAGS="-s -w -X main.Version=${VERSION}"
          CMDPATH=./cmd/v2gen/
          GOOS=linux GOARCH=amd64 go build -ldflags="${LDFLAGS}" -gcflags=-trimpath=${GOPATH} -asmflags=-trimpath=${GOPATH} -v -o ./build/v2gen_amd64_linux ${CMDPATH}
          GOOS=linux GOARCH=arm64 go build -ldflags="${LDFLAGS}" -gcflags=-trimpath=${GOPATH} -asmflags=-trimpath=${GOPATH} -v -o ./build/v2gen_arm64_linux ${CMDPATH}
          GOOS=linux GOARCH=386 go build -ldflags="${LDFLAGS}" -gcflags=-trimpath=${GOPATH} -asmflags=-trimpath=${GOPATH} -v -o ./build/v2gen_386_linux ${CMDPATH}
          GOOS=linux GOARCH=arm go build -ldflags="${LDFLAGS}" -gcflags=-trimpath=${GOPATH} -asmflags=-trimpath=${GOPATH} -v -o ./build/v2gen_arm_linux ${CMDPATH}
          GOOS=windows GOARCH=amd64 go build -ldflags="${LDFLAGS}" -gcflags=-trimpath=${GOPATH} -asmflags=-trimpath=${GOPATH} -v -o ./build/v2gen_amd64_windows.exe ${CMDPATH}
          GOOS=windows GOARCH=386 go build -ldflags="${LDFLAGS}" -gcflags=-trimpath=${GOPATH} -asmflags=-trimpath=${GOPATH} -v -o ./build/v2gen_386_windows.exe ${CMDPATH}
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="${LDFLAGS} -extldflags \"-static\"" -gcflags=-trimpath=${GOPATH} -asmflags=-trimpath=${GOPATH} -v -o ./build/v2gen_amd64_linux_static ${CMDPATH}

      - name: compress
        uses: actions-github/upx@master
        with:
          dir: './build'
          upx_args: '-9'

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./build/v2gen_amd64_linux
            ./build/v2gen_arm64_linux
            ./build/v2gen_386_linux
            ./build/v2gen_arm_linux
            ./build/v2gen_amd64_windows.exe
            ./build/v2gen_386_windows.exe
            ./build/v2gen_amd64_linux_static
            ./LICENSE
            ./README.md
            ./README_zh_cn.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

