name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15]
        platform: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: set variables
        run: |
          mkdir build
          echo "GOPRIVATE=github.com/v2ray/v2ray-core" >> $GITHUB_ENV

      - name: Test
        run: go test ./... -v